name: TestPushECR

on:
  push:
    branches: ['main', 'production']

jobs:
  push-to-ecr-staging:
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: staging
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          AAA: ${{ secrets.STAGINS }}
        run: |
          echo $AAA
          
  push-to-ecr-production:
    if: ${{ github.ref == 'refs/heads/production' }}
    environment:
      name: production
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          AAA: ${{ secrets.AAAA }}
        run: |
          echo "${GITHUB_REF}"
